/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./pages/LoginPage.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    HeaderBar: typeof import('./components/kbLayout/HeaderBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IHeroiconsOutlineBars3: typeof import('~icons/heroicons-outline/bars3')['default']
    IHeroiconsOutlineBars3Icon: typeof import('~icons/heroicons-outline/bars3-icon')['default']
    IHeroiconsOutlineBell: typeof import('~icons/heroicons-outline/bell')['default']
    IHeroiconsOutlineBellIcon: typeof import('~icons/heroicons-outline/bell-icon')['default']
    IHeroiconsOutlineChevron: typeof import('~icons/heroicons-outline/chevron')['default']
    IHeroiconsOutlineChevronDown: typeof import('~icons/heroicons-outline/chevron-down')['default']
    IHeroiconsOutlineChevronDownIcon: typeof import('~icons/heroicons-outline/chevron-down-icon')['default']
    IHeroiconsOutlineHome: typeof import('~icons/heroicons-outline/home')['default']
    IHeroiconsOutlineMagnifyingGlass: typeof import('~icons/heroicons-outline/magnifying-glass')['default']
    IHeroiconsOutlineMagnifyingGlassIcon: typeof import('~icons/heroicons-outline/magnifying-glass-icon')['default']
    IHeroiconsOutlineX: typeof import('~icons/heroicons-outline/x')['default']
    IHeroiconsOutlineXMark: typeof import('~icons/heroicons-outline/x-mark')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    PopupSidebar: typeof import('./components/kbLayout/PopupSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaticSideBar: typeof import('./components/kbLayout/StaticSideBar.vue')['default']
    TopNav: typeof import('./components/nav/TopNav.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    UserProfileEdit: typeof import('./components/UserProfileEdit.vue')['default']
  }
}
